// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button'];
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox'];
    ACol: typeof import('ant-design-vue/es')['Col'];
    ACollapse: typeof import('ant-design-vue/es')['Collapse'];
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel'];
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider'];
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker'];
    AEmpty: typeof import('ant-design-vue/es')['Empty'];
    AForm: typeof import('ant-design-vue/es')['Form'];
    AFormItem: typeof import('ant-design-vue/es')['FormItem'];
    AInput: typeof import('ant-design-vue/es')['Input'];
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber'];
    ALayout: typeof import('ant-design-vue/es')['Layout'];
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider'];
    AMenu: typeof import('ant-design-vue/es')['Menu'];
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
    AModal: typeof import('ant-design-vue/es')['Modal'];
    APagination: typeof import('ant-design-vue/es')['Pagination'];
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm'];
    APopover: typeof import('ant-design-vue/es')['Popover'];
    ARadio: typeof import('ant-design-vue/es')['Radio'];
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup'];
    ARow: typeof import('ant-design-vue/es')['Row'];
    ASelect: typeof import('ant-design-vue/es')['Select'];
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption'];
    ASwitch: typeof import('ant-design-vue/es')['Switch'];
    ATable: typeof import('ant-design-vue/es')['Table'];
    ATextarea: typeof import('ant-design-vue/es')['Textarea'];
    ATooltip: typeof import('ant-design-vue/es')['Tooltip'];
    AUpload: typeof import('ant-design-vue/es')['Upload'];
    CaretDownOutlined: typeof import('@ant-design/icons-vue')['CaretDownOutlined'];
    LeftOutlined: typeof import('@ant-design/icons-vue')['LeftOutlined'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SearchOutlined: typeof import('@ant-design/icons-vue')['SearchOutlined'];
    UploadOutlined: typeof import('@ant-design/icons-vue')['UploadOutlined'];
  }
}
